# Generated by Django 3.2.4 on 2021-07-30 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 12, 19, 1, 509498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 12, 19, 1, 510508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 12, 19, 1, 509498, tzinfo=utc)),
        ),
    ]
