# Generated by Django 3.2.4 on 2023-05-17 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 24, 54, 811737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 24, 54, 811737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 24, 54, 811737, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.CharField(max_length=400)),
                ('comment_by', models.CharField(max_length=400)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
