# Generated by Django 3.2.4 on 2023-05-17 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230517_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='comment',
            field=models.CharField(default='This is great', max_length=900),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 39, 59, 495152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 39, 59, 495152, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 9, 39, 59, 495152, tzinfo=utc)),
        ),
    ]
